# Generated by Django 3.2.18 on 2023-10-10 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan_amount', models.FloatField(default=0.0)),
                ('paid_amount', models.FloatField(default=0.0)),
                ('loan_term', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('PDG', 'Pending'), ('AVD', 'Approved'), ('RJD', 'Rejected'), ('PAID', 'Paid')], default='PDG', max_length=7)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_approved_by', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoanTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('term_amount', models.FloatField(default=0.0)),
                ('paid_amount', models.FloatField(default=0.0)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('PDG', 'Pending'), ('PAID', 'Paid')], default='PDG', max_length=7)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aspireloan.loan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoanRepaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repayment_amount', models.FloatField(default=0.0)),
                ('loan_term_id', models.PositiveIntegerField()),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aspireloan.loan')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
