# Generated by Django 3.2.18 on 2023-10-10 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('digest', models.CharField(max_length=128, unique=True)),
                ('token_key', models.CharField(db_index=True, max_length=8)),
                ('is_mobile', models.BooleanField(default=False)),
                ('device_name', models.CharField(blank=True, max_length=255, null=True)),
                ('os_name', models.CharField(blank=True, max_length=255, null=True)),
                ('os_version', models.CharField(blank=True, max_length=255, null=True)),
                ('browser_name', models.CharField(blank=True, max_length=255, null=True)),
                ('browser_version', models.CharField(blank=True, max_length=255, null=True)),
                ('app_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('expires_on', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
